version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: bs-backend
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/home/node/app
  redis:
    image: redis:alpine
    container_name: bs-test-redis
    ports:
      - "6379:6379"