version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: beauty-space-backend
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/home/node/app
